// Code generated by Slice Machine. DO NOT EDIT.

import Biography from './Biography/index.svelte';
import ContentIndex from './ContentIndex/index.svelte';
import Experience from './Experience/index.svelte';
import Hero from './Hero/index.svelte';
import ImageBlock from './ImageBlock/index.svelte';
import ProductList from './ProductList/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	biography: Biography,
	content_index: ContentIndex,
	experience: Experience,
	hero: Hero,
	image_block: ImageBlock,
	product_list: ProductList,
	rich_text: RichText
};
